services:
  - type: web
    name: instagram-script-writer
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: PINECONE_INDEX
        value: scriptwriter-384
      - key: PINECONE_HOST
        sync: false