name: Telugu Scraper Weekly Refresh

on:
  schedule:
    # Run weekly on Sunday at midnight
    - cron: "0 0 * * 0"
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape_and_ingest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Telugu scraper and ingestion
        run: |
          # Create necessary directories
          mkdir -p data/raw_reels/Telugu scripts/auto_telugu

          # Run the full pipeline
          python src/run_all.py --mode scraper
          python src/run_all.py --mode ingest

        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_HOST: ${{ secrets.PINECONE_HOST }}
          PINECONE_INDEX: ${{ secrets.PINECONE_INDEX }}
          PINECONE_METRIC: cosine
          PINECONE_DIMENSIONS: 1024
          PINECONE_CLOUD: aws
          PINECONE_REGION: ${{ secrets.PINECONE_REGION }}
          PINECONE_TYPE: dense
          PINECONE_CAPACITY_MODE: serverless
          EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL || 'llama-text-embed-v2' }}
          INSTA_USERNAME: ${{ secrets.INSTA_USERNAME || '' }}
          INSTA_PASSWORD: ${{ secrets.INSTA_PASSWORD || '' }}
          TARGET_HASHTAG: Telugu
          MAX_FETCH: 200
          RAW_DIR: data/raw_reels
          TOP_CSV: data/top_reels.csv
          SCRIPT_DIR: scripts/auto_telugu
